#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '


if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi



PS1='\[\e[38;5;157m\]🌏\[\e[m\] \[\e[38;5;226m\]\u\[\e[38;5;129m\]🪐\[\e[m\]\[\e[38;5;226m\]\h\[\e[38;5;197m\] \w \[\e[38;5;157m\]🌍\[\e[m\] \[\033[38;5;129m\n '


neofetch
